name: picto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.6
  dio: ^5.7.0
  http: ^1.2.2
  get: ^4.6.6
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  kakao_map_plugin: ^0.3.2
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/assets/common/
    - lib/assets/list/
    - lib/assets/map/
    - lib/assets/navigator/
    - lib/assets/sign_in/
    - lib/assets/testimage/
