name: picto
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  http: ^1.2.2
  get: ^4.6.6
  lucide_icons: ^0.257.0
  web_socket_channel: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/common/
    - lib/assets/list/
    - lib/assets/map/
    - lib/assets/navigator/
    - lib/assets/sign_in/
    - lib/assets/testimage/
